name: 'beer_analytics'
version: '1.0.0'
config-version: 2

profile: dbt_beers_test

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

seeds:
  beer_analytics:
    +enabled: true
    seed_beers:
      +schema: seed_beers
      seed_beers:
        +column_types:
            ibu: decimal
            abv: decimal

models:
    +transient: false
    beer_analytics:
        intermediate:
            int_beers:
                +schema: int_beers
            int_sales:
                +schema: int_sales
        mart:
            mart_beers:
                +schema: mart_beers
            mart_sales:
                +schema: mart_sales
        staging:
            stg_beers:
                +schema: stg_beers
            stg_sales:
                +schema: stg_sales
