dbt_beers_test:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: DBT_BEERS_ROLE
      database: DBT_BEERS_DEV_DAN #change if you're not using ~/.dbt/profiles.yml
      warehouse: DBT_BEERS_WH
      schema: default_schema
      threads: 4
    pr:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: DBT_BEERS_ROLE
      database: "{{ env_var('PR_DATABASE') | as_text }}"
      warehouse: DBT_BEERS_WH
      schema: default_schema
      threads: 4
    production:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: DATAFOLDROLE
      database: DBT_BEERS_PROD
      warehouse: INTEGRATION
      schema: default_schema
      threads: 4
